version: "3"
services:
  node-api:
    image: node-api-jest:0.1
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #     - ./.env
    # environment:
    #   - DATABASE_HOSTNAME=postgres
    #   - DATABASE_PORT=5432
    #   - DATABASE_PASSWORD=password123
    #   - DATABASE_NAME=fastapi
    #   - DATABASE_USERNAME=postgres
    #   - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    #   - ALGORITHM=HS256
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: npm run dev